### ISSUE TITLE
Download Command IE Error

### ISSUE THREAD

**Issue by stealthbird77** [echo3/echo3filetransfer#5]
IE 7 and IE 6 both have a bug that is precluding downloads over ssl.

To fix I downloaded the file transfer code and patched package nextapp.echo.filetransfer.webcontainer.service.DownloadService.java as follows:

```
    provider.writeFile(out);
```

to this:

```
    response.setHeader( "Cache-Control", "" );
    response.setHeader( "Pragma", "" );
    provider.writeFile(out);
```

I recommend that this be applied to Echo3 file transfer stuff as I don't see any errors it could cause and helps to alleviate some bugs

I have been running this fix in production for about 1 year with no issue.  I recently re-downloaded the source code and had to reapply this fix.  I though I'd send in an issue.

Thank you.

**Comment by bentolor** [comment]
Thanks for your report. I can confirm this bug - we also stumbled over it.

@ceari maybe you can integrate this fix?
