### ISSUE TITLE
filetransfer-3.0.2 VersionRangeResolutionException

### ISSUE THREAD

**Issue by stefanharjes** [echo3/echo3filetransfer#9]
Hi echo3,

when I try to include the echo3-filetransfer dependencies (via maven pom.xml) I get the above exception simply when writing the dependencies into the pom.xml. 

Any hints?
Cheers
Stefan

**Comment by ceari** [comment]
I think this issue was described and fixed for version 3.0.3 in http://bugs.nextapp.com/mantis/view.php?id=521 but 3.0.3 has not been published on Maven Central yet. It's available on Github for installation into the local repository though: https://github.com/echo3/echo3filetransfer/releases

**Comment by bentolor** [comment]
No clue, why this was left out in the first place.

I just rebuilt, uploaded and released 3.0.3 following our documented [Release Process](https://github.com/echo3/echo3/wiki/Release-Process)

It will take a few minutes before the new version becomes visible on Maven central. You can [check it here](http://search.maven.org/#search|ga|1|g%3A%22com.nextapp%22%20AND%20a%3A%22echo3-filetransfer%22)

Hope this helps!
